### ISSUE TITLE
Searchbar

### ISSUE THREAD

**Issue by kssoz** [freifunkks/meshviewer#1]
A searchbar would be good to be able to filter certain parts of the net to be shown.
example: https://map.darmstadt.freifunk.net/

**Comment by jplatte** [comment]
I don't see a searchbar on the site you linked... And in general I didn't plan to develop meshviewer further, at least not seperately from upstream (ffnord). Why did you report this as an issue with our fork?

**Comment by kssoz** [comment]
look there is (Hostname X) in the darmstadt map

**Comment by jplatte** [comment]
Yeah, that has to be the filter feature on the other branch. Should be easy to get running for us too, I don't have time until next week though. I initially didn't understand what it was for because the input field is hidden by default.
