### ISSUE TITLE
Mesh stats

### ISSUE THREAD

**Issue by kssoz** [freifunkks/meshviewer#2]
The stats currently shown in the map are: "xxx nodes (xxx online, x new, x lost) with xxxx clients". To encourage freifunkers to care about the freifunk net autonomy, it would be a good thing to represent the **mesh** somehow. 

There are several possibilities to calculate how much of the net already meshes.
example:https://freifunk-kassel.de/ffmeshgame

- One simple variable is `<<FFLinkPercentage()>>` which represents the number of nodes linked to other nodes by wifi compared to all nodes.
- Another idea is to meassure the net fragmentation. This would be counting wifi-mesh-islands and relating it to the whole net. Common metrics of netanalysis can be found on [wikipedia.de](https://de.wikipedia.org/wiki/Soziale_Netzwerkanalyse#Ma.C3.9Fzahlen.2FAnalyseverfahren)

**Comment by jplatte** [comment]
Okay, I don't know who you are but apparently you're from inside our community. `FFLinkPercentage` is a plugin in our MoinMoin, this can't be used in the Meshviewer. I'd happily discuss how to improve the meshviewer, but the issue system on GitHub doesn't seem like a good place for that. I'd suggest using IRC.

**Comment by kssoz** [comment]
Please don't close unsolved issues, just let them idle, so that others may look into it. I think github is a good place to propose and discuss features.
