### ISSUE TITLE
mesh/map button

### ISSUE THREAD

**Issue by kssoz** [freifunkks/meshviewer#5]
The button design does not toggle like described on https://freifunk-kassel.de/Karte

**Comment by jplatte** [comment]
Could you please stop opening issues on this repository? Apart from that I have no idea what you mean.

**Comment by kssoz** [comment]
Just because you don't find the problem, it won't disappear. Der Augenbutton hat vorher getoggelt und das steht auch so in der Anleitung unter der Karte auf der webseite. 

![mapbutton](https://cloud.githubusercontent.com/assets/3306219/11420113/2c639f2e-942c-11e5-9512-9ef8b6f07dab.jpg)

**Comment by icks** [comment]
This is a problem concerning content of the wiki. It has absolutely nothing to do with the code of the plugin.

**Comment by kssoz** [comment]
That is a point of view problem: Before, there was a toggle button in the map - now there isn't. That is why the wiki descriptions don't match any longer, also the tutorial pdf is now outdated. Interdependencies.

**Comment by icks** [comment]
Then please go and fix it on the wiki page yourself. The description found on the wiki has nothing to do with the meshviewer itself.

**Comment by kssoz** [comment]
The description doesn't describe anything else but the meshviewer. The meshviewer has changed undeniable. If you think it's better with the new eye button... ok. If you think a pdf or wiki code is less important than other code... ok. Change the description yourself then.

**Comment by jplatte** [comment]
Fixed the wiki text.
