### ISSUE TITLE
"Node Offline" Notification

### ISSUE THREAD

**Issue by kssoz** [freifunkks/meshviewer#6]
If a node goes down, there should be an automatically triggered email to the node owner, asking for the reason, offering help via hallo@freiffunk-kassel.de 

**Keeping a node owner is easier than hunting for new ones.**

(No idea where to put this issue else than here... The meshviewer is commonly used for monitoring the freifunk net. It is the service people use to see which routers are offline or which links are in a bad state.)

**Comment by icks** [comment]
I have this on my mind. Will most likely be realized as a cronjob on one of the gateways.

**Comment by jplatte** [comment]
Closing as it has absolutely nothing to do with the meshviewer. Please create an issue on the salt-conf repository if you really want to keep track of this via GitHub.
