### ISSUE TITLE
2clicks for coordinates bug

### ISSUE THREAD

**Issue by kssoz** [freifunkks/meshviewer#7]
To get the geo coordinates (e.g. to config new nodes) there is a nice point and click icon implemented in the meshviewer map. After clicking on that icon, it is necessary to click 2 times to get the geo-data. 

(32c3 JPlatte had this fixed - not implemented?)

**Comment by jplatte** [comment]
It's fixed, I simply didn't update our installation yet. Thanks for reminding me though, I'll do it now.
